### ISSUE TITLE
[需求]支持DeepL的api，以及仅翻译标题

### ISSUE THREAD

**Issue by toyo2333** [rcy1314/Rss-Translation#6]
1、希望支持DeepL的api翻译（使用者自己提供key），经过我几个月的日常翻译新闻使用。DeepL好于谷歌翻译以及GTP3.5很多。希望支持。

2、希望支持仅翻译标题（其他内容保留原始fee的内容），原因是一些新闻阅读是只需要看下标题才知道是否需要进一步深度阅读（在这之前其实没必要把内容也翻译了）这个希望可以提供一个选项，方便使用者后续自行决定后续动作。另外就是如果后面通过api进行翻译，这样也可以减少token消耗，很有效的使用付费翻译服务。

谢谢。很好的工具。

希望上述建议可以得到反馈，和处理。

**Comment by toyo2333** [comment]
仅翻译标题我改了改，ok了。deepL后面我自己试一试。

有个问题：这3小时更新一次。如果目标源3小时之内更新了20条，但代码里只设定拉取10条。是不是意味着有10条就丢了？

**Comment by toyo2333** [comment]
这两个功能我自己改好了。

另外就是确认会丢数据，如果目标源的更新频率高的话，max设置为10就丢挺多了。

总体来说挺好用。

另外就是你那个openai的代码是有bug的，缺少一些库和completions的使用会报错。

openai普通api的翻译，一个feed还没翻完就429错误了。没法用，还是建议deepL的key会好很多。米有rpm限制。

**Comment by rcy1314** [comment]
> 这两个功能我自己改好了。
> 
> 另外就是确认会丢数据，如果目标源的更新频率高的话，max设置为10就丢挺多了。
> 
> 总体来说挺好用。
> 
> 另外就是你那个openai的代码是有bug的，缺少一些库和completions的使用会报错。
> 
> openai普通api的翻译，一个feed还没翻完就429错误了。没法用，还是建议deepL的key会好很多。米有rpm限制。

嗯，其实自己改是最好的的了

**Comment by toyo2333** [comment]
> > 这两个功能我自己改好了。
> > 另外就是确认会丢数据，如果目标源的更新频率高的话，max设置为10就丢挺多了。
> > 总体来说挺好用。
> > 另外就是你那个openai的代码是有bug的，缺少一些库和completions的使用会报错。
> > openai普通api的翻译，一个feed还没翻完就429错误了。没法用，还是建议deepL的key会好很多。米有rpm限制。
> 
> 嗯，其实自己改是最好的的了

我不懂编程的，我就是把代码和需求丢给GTP，然后搞几轮，就搞定了。。总体来说。很赞！感谢作者！
