### ISSUE TITLE
建议对link，guid部分也做符号转义，以及修改一下requirements.txt

### ISSUE THREAD

**Issue by tjsky** [rcy1314/Rss-Translation#7]
- 对link，guid部分也做特符转义：
比如BBC的的RSS源内网址内的`&`会导致XML格式错误
![_20231124105445](https://github.com/rcy1314/Rss-Translation/assets/7272911/855d0fc8-6a2d-4e1c-9c74-7a520557f5ee)

- 修改一下requirements.txt
 1. 去掉`time、hashlib、sys、os`等标准库内置的组件
本地大家还是习惯用pip install -r requirements.txt安装依赖
直接执行会报错
```shell
ERROR: Could not find a version that satisfies the requirement time (from versions: none)
ERROR: No matching distribution found for time
```

**Comment by smilingpoplar** [comment]
发现[Bingtrans.py](https://github.com/rcy1314/Rss-Translation/blob/main/Bingtrans.py)中用的`mtranslate`其实是 google translate 😓

**Comment by rcy1314** [comment]
@tjsky 可以修改requirements.txt，但特符转义我还不知道如何具体修改，如你提到的这个，在其它RSS链接和自制RSS里也容易报错，但有时它又是正常的

**Comment by rcy1314** [comment]
> 发现[Bingtrans.py](https://github.com/rcy1314/Rss-Translation/blob/main/Bingtrans.py)中用的`mtranslate`其实是 google translate 😓

这个...我不太懂，稍后会进行修改，如果非要bing,只能API

**Comment by tjsky** [comment]
> @tjsky 可以修改requirements.txt，但特符转义我还不知道如何具体修改，如你提到的这个，在其它RSS链接和自制RSS里也容易报错，但有时它又是正常的

![_20231127084733](https://github.com/rcy1314/Rss-Translation/assets/7272911/3b6ec078-7565-4af8-8337-974ca6fc84d6)
目前主要是还是`&`导致的错误，仿照对description的方式，替换一下就好了。

**Comment by rcy1314** [comment]
> > @tjsky 感谢，已调整

**Comment by smilingpoplar** [comment]
@rcy1314  应该是调整requirement.txt，然后workflow中python环境用`pip install -r requirements.txt`安装

**Comment by rcy1314** [comment]
@smilingpoplar 我改了requirement.txt及转义问题，但workflow中python环境是为方便自由切换不同的翻译PY文件，满足不同文件的依赖，所以不是pip install -r requirements.txt【本来一开始requirements.txt也是为这个目的，所以才会开始加入更多依赖组件的加入】
